#
# Paperbot configuration
#

# Places to publish paper suggestions (names of sections, below)
destinations = []

# Number of papers to publish -- at most one from each source.
# Set to 0 to publish a paper from all sources.
publish = 0

[papers_we_love]
# Path to locally cloned Papers We Love git repo.
path = "~/projects/forked/papers-we-love"

# URL of remote Papers We Love git repo.
url = "https://github.com/papers-we-love/papers-we-love"

[lobsters]
rss = https://lobste.rs/rss
url = https://lobste.rs

[history]
# History buffer containing the last `depth` suggested papers, which will not
# be suggested again until they leave the history buffer.
path = "history.txt"
depth = 442

[discord]
# Credentials file contains a single toml entry:
#   url = "<url>"
credentials = "discord.toml"

[bluesky]
# Credentials file contains two toml entries:
#   user = "<user>"
#   pw = "<password>"
credentials = "bluesky.toml"
